import{a as b,S as w,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();async function y(s,r,o){return await b.get(`https://pixabay.com/api/?q=${s}&image_type=photo&orientation=horizontal&safesearch=true&key=47508443-dec4cffb8f44668b6640702d9`,{params:{page:r,per_page:o}})}function g(s){return s.map(({webformatURL:r,largeImageURL:o,tags:a,likes:e,views:t,comments:i,downloads:u})=>`<li class="list-item" >
  <a href="${o}" alt="${a}" title=""/>
    <img src="${r}" alt="${a}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${t}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${i}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${u}</span></p>
  </div></a>
</li>`).join("")}const L=new w(".gallery a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),P=document.querySelector(".form"),f=document.querySelector(".gallery"),p=document.querySelector(".loader"),n=document.querySelector(".more-btn"),h=15;let d=1,m=1,c;P.addEventListener("submit",$);n.addEventListener("click",S);function $(s){s.preventDefault();const{picture:r}=s.target.elements;c=r.value.trim(),f.innerHTML="",(!c||c===" ")&&l.show({title:":(",message:"Please add request!",position:"center",color:"red"}),d=1,p.classList.replace("hidden","loader"),n.classList.replace("more-btn","hidden");async function o(a,e,t){try{const{data:{hits:i,totalHits:u}}=await y(a,e,t);m=Math.ceil(u/t),i.length?(f.innerHTML=g(i),L.refresh(),e>=m?n.classList.replace("more-btn","hidden"):n.classList.replace("hidden","more-btn")):l.show({title:"X",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"})}catch(i){l.show({title:"X",message:`${i.message}`,position:"center",color:"red"})}finally{n.disabled=!1,p.classList.replace("hidden","loader")}}o(c,d,h)}async function S(){d+=1,n.disabled=!0,p.classList.replace("hidden","loader");try{const{data:{hits:s,totalHits:r}}=await y(c,d,h);f.insertAdjacentHTML("beforeend",g(s)),m=Math.ceil(r/h),d===m&&(n.classList.replace("more-btn","hidden"),l.show({title:"X",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}));const a=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"}),L.refresh()}catch(s){l.show({title:"X",message:`${s.message}`,position:"center",color:"red"})}finally{n.disabled=!1,p.classList.replace("hidden","loader")}}
//# sourceMappingURL=index.js.map
