import{S as u,i as a}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();function m(o){return fetch(`https://pixabay.com/api/?q=${o}&image_type=photo&orientation=horizontal&safesearch=true&key=47508443-dec4cffb8f44668b6640702d9`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()})}function d(o){return o.map(({webformatURL:r,largeImageURL:i,tags:t,likes:e,views:s,comments:n,downloads:p})=>`<li class="list-item" >
  <a href="${i}" alt="${t}" title=""/>
    <img src="${r}" alt="${t}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${s}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${n}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${p}</span></p>
  </div></a>
</li>`).join("")}const f=new u(".gallery a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),h=document.querySelector(".form"),c=document.querySelector(".gallery"),l=document.querySelector(".loader");h.addEventListener("submit",g);function g(o){o.preventDefault();const{picture:r}=o.target.elements,i=r.value.trim();if(c.innerHTML="",!i||i===""){a.show({title:":(",message:"Please add request!",position:"topRight",color:"red"}),c.innerHTML=":(";return}l.classList.remove("hidden"),m(i).then(t=>{t.hits.length?(c.innerHTML=d(t.hits),f.refresh()):a.show({title:"X",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"})}).catch(t=>{a.show({title:"X",message:`${t.message}`,position:"topRight",color:"red"})}).finally(()=>{r.value="",l.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
